data_loader:
  batch_size: 4
  data_path: emopia_events/lead_sheet_chord11_{}/events
  train_split: emopia_events/data_splits/train.pkl
  val_split: emopia_events/data_splits/valid.pkl
  vocab_path: emopia_events/lead_sheet_chord11_{}/dictionary.pkl
model:
  d_embed: 512
  d_ff: 2048
  d_model: 512
  feature_map:
    n_dims: 128
  max_len: 1024
  n_head: 8
  n_layer: 12
  use_segemb: true
  n_segment_types: 2
training:
  ckpt_dir: ckpt/emopia_lead_sheet_chord11_{}
  ckpt_interval: 1
  feat_redraw_prob: 0.05
  gpuid: 0
  log_interval: 50
  lr: 0.00001
  lr_scheduler:
    T_max: 500000
    eta_min: 1.0e-06
  num_epochs: 100
  trained_optim: null
  trained_params: null
  warmup_steps: 200
