data_loader:
  batch_size: 8
  data_path: hooktheory_events/lead_sheet_chord11_{}/events
  train_split: hooktheory_events/data_splits/train.pkl
  val_split: hooktheory_events/data_splits/valid.pkl
  vocab_path: hooktheory_events/lead_sheet_chord11_{}/dictionary.pkl
model:
  d_embed: 512
  d_ff: 2048
  d_model: 512
  feature_map:
    n_dims: 128
  max_len: 1024
  n_head: 8
  n_layer: 12
  use_segemb: true
  n_segment_types: 2
training:
  ckpt_dir: ckpt/hooktheory_{}
  ckpt_interval: 5
  feat_redraw_prob: 0.05
  gpuid: 0
  log_interval: 50
  lr: 0.0001
  lr_scheduler:
    T_max: 500000
    eta_min: 1.0e-05
  num_epochs: 100
  trained_optim: null
  trained_params: null
  warmup_steps: 200
